In [2]:
%%HTML
<h2> NumPy Basics </h2>

In [2]:
import numpy as np
a = np.zeros(3)
a

array([ 0.,  0.,  0.])

In [4]:
type(a)

numpy.ndarray

<h2> Shape and Dimension </h2>

In [5]:
z = np.zeros(10)
z.shape


(10L,)

In [6]:
z.shape = (10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [7]:
z = np.zeros(10)
z.shape = (2,5)
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<h2> Creating Arrays </h2>

In [8]:
z = np.empty(3)
z

array([0., 0., 0.])

In [9]:
z = np.linspace(2, 4, 5)  # From 2 to 4, with 5 elements
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [3]:
z = np.identity(2, dtype = int)
z

array([[1, 0],
       [0, 1]])

In [11]:
z = np.array([10, 20])                 # ndarray from Python list
z

array([10, 20])

In [12]:
z = np.array((10, 20), dtype=float)    # Here 'float' is equivalent to 'np.float64'
z

array([10., 20.])

In [13]:
z = np.array([[1, 2], [3, 4]])         # 2D array from a list of lists
z

array([[1, 2],
       [3, 4]])

<h2> Array Indexing </h2>

In [14]:
z = np.linspace(1, 2, 9)
z

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [15]:
z[0]

1.0

In [16]:
z[0:2]  # Two elements, starting at element 0


array([1.   , 1.125])

In [17]:
z[-1]

2.0

In [18]:
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [19]:

z[1, 1]

4

In [20]:
z[0, 0]

1

In [21]:
z[1,0]

3

In [22]:
z[0, :]


array([1, 2])

In [23]:
z[1, :]

array([3, 4])

In [24]:
z[:,1]

array([2, 4])

In [25]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [26]:
indices = np.array((0, 2, 3))
z[indices]

array([2. , 3. , 3.5])

In [27]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)
d

array([False,  True,  True, False, False])

In [28]:
z[d]

array([2.5, 3. ])

In [29]:
z = np.empty(3)
z


array([2. , 3. , 3.5])

In [30]:
z[:] = 42
z

array([42., 42., 42.])

<h2> Array Methods </h2>

In [31]:
a = np.array((4, 3, 2, 1))
a

array([4, 3, 2, 1])

In [32]:
a.sort()              # Sorts a in place
a

array([1, 2, 3, 4])

In [33]:
a.sum()

10

In [34]:
a.mean()

2.5

In [35]:
a.max()               # Max

4

In [36]:
a.argmax()            # Returns the index of the maximal element


3

In [37]:
a.cumsum()            # Cumulative sum of the elements of a


array([ 1,  3,  6, 10])

In [38]:
a.cumprod()           # Cumulative product of the elements of a


array([ 1,  2,  6, 24])

In [39]:
a.var()               # Variance


1.25

In [40]:
a.std()               # Standard deviation

1.118033988749895

In [41]:
a

array([1, 2, 3, 4])

In [42]:
a.shape = (2, 2)
a

array([[1, 2],
       [3, 4]])

In [43]:
a.T     # Equivalent to a.transpose()

array([[1, 3],
       [2, 4]])

<h2> Operations on Arrays </h2>

In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [45]:
a * b

array([ 5, 12, 21, 32])

In [46]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[2., 2.],
       [2., 2.]])

In [47]:
A * B

array([[1., 1.],
       [1., 1.]])

<h2> Matrix Multiplication </h2>

In [48]:
A = np.ones((2, 2))
B = np.ones((2, 2))
np.matmul(A,B)

array([[2., 2.],
       [2., 2.]])

In [49]:
A = np.ones((2, 2))
B = np.ones((2, 2))
np.dot(A,B)

array([[2., 2.],
       [2., 2.]])

<h2> Vectorized Functions </h2>

In [50]:
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [51]:
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)

array([0.24197072, 0.05399097, 0.00443185])

In [52]:
x = np.random.randn(4)
x

array([0.01736346, 1.18480666, 0.40330262, 2.13028671])

In [53]:
np.where(x > 0, 1, 0)  # Insert 1 if x > 0 true, otherwise 0

array([1, 1, 1, 1])

<h2> Subpackages </h2>

In [54]:
z = np.random.randn(10000)  # Generate standard normals
y = np.random.binomial(10, 0.5, size=1000)    # 1,000 draws from Bin(10, 0.5)
y.mean()

4.996

In [55]:
A = np.array([[1, 2], [3, 4]])

np.linalg.det(A)           # Compute the determinant

-2.0000000000000004

In [56]:
np.linalg.inv(A) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

<h2> Exercise </h2>

In [72]:
def p(x, coef):
    X = np.empty(len(coef))
    X[0] = 1
    X[1:] = x
    y = np.cumprod(X)   # y = [1, x, x**2,...]
    return np.matmul(coef,y)

In [73]:
coef = np.ones(3)
print(coef)
print(p(1, coef))
# For comparison
q = np.poly1d(coef)
print(q(1))

[1. 1. 1.]
3.0
3.0


In [9]:
from itertools import product
set_one = ([0.25, 0.33, 0.45], [0.4], [0.1])
for a,b,c in product([0.25, 0.33, 0.45], [0.4], [0.1]):
    print (a,b,c)

0.25 0.4 0.1
0.33 0.4 0.1
0.45 0.4 0.1
