In [ ]:
%%HTML
<h2> NumPy Basics </h2>

In [2]:
import numpy as np
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
type(a)

<h2> Shape and Dimension </h2>

In [ ]:
z = np.zeros(10)
z.shape


In [ ]:
z.shape = (10,1)
z

In [ ]:
z = np.zeros(10)
z.shape = (2,5)
z

<h2> Creating Arrays </h2>

In [3]:
z = np.empty(3)
z

array([0., 0., 0.])

In [6]:
z = np.linspace(2, 4, 5)  # From 2 to 4, with 5 elements
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [7]:
z = np.identity(2)
z

array([[1., 0.],
       [0., 1.]])

In [8]:
z = np.array([10, 20])                 # ndarray from Python list
z

array([10, 20])

In [9]:
z = np.array((10, 20), dtype=float)    # Here 'float' is equivalent to 'np.float64'
z

array([10., 20.])

In [10]:
z = np.array([[1, 2], [3, 4]])         # 2D array from a list of lists
z

array([[1, 2],
       [3, 4]])

<h2> Array Indexing </h2>

In [14]:
z = np.linspace(1, 2, 9)
z

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [15]:
z[0]

1.0

In [16]:
z[0:2]  # Two elements, starting at element 0


array([1.   , 1.125])

In [17]:
z[-1]

2.0

In [18]:
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [20]:

z[1, 1]

4

In [21]:
z[0, 0]

1

In [22]:
z[1,0]

3

In [23]:
z[0, :]


array([1, 2])

In [24]:
z[1, :]

array([3, 4])

In [25]:
z[:,1]

array([2, 4])

In [34]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [35]:
indices = np.array((0, 2, 3))
z[indices]

array([2. , 3. , 3.5])

In [36]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)
d

array([False,  True,  True, False, False])

In [37]:
z[d]

array([2.5, 3. ])

In [38]:
z = np.empty(3)
z


array([2. , 3. , 3.5])

In [39]:
z[:] = 42
z

array([42., 42., 42.])

<h2> Array Methods </h2>

In [40]:
a = np.array((4, 3, 2, 1))
a

array([4, 3, 2, 1])

In [41]:
a.sort()              # Sorts a in place
a

array([1, 2, 3, 4])

In [42]:
a.sum()

10

In [43]:
a.mean()

2.5

In [44]:
a.max()               # Max

4

In [45]:
a.argmax()            # Returns the index of the maximal element


3

In [46]:
a.cumsum()            # Cumulative sum of the elements of a


array([ 1,  3,  6, 10])

In [47]:
a.cumprod()           # Cumulative product of the elements of a


array([ 1,  2,  6, 24])

In [48]:
a.var()               # Variance


1.25

In [49]:
a.std()               # Standard deviation

1.118033988749895

In [50]:
a

array([1, 2, 3, 4])

In [51]:
a.shape = (2, 2)
a

array([[1, 2],
       [3, 4]])

In [52]:
a.T     # Equivalent to a.transpose()

array([[1, 3],
       [2, 4]])

<h2> Operations on Arrays </h2>

In [53]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [54]:
a * b

array([ 5, 12, 21, 32])

In [55]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[2., 2.],
       [2., 2.]])

In [56]:
A * B

array([[1., 1.],
       [1., 1.]])

<h2> Matrix Multiplication </h2>

In [60]:
A = np.ones((2, 2))
B = np.ones((2, 2))
np.matmul(A,B)

array([[2., 2.],
       [2., 2.]])

In [63]:
A = np.ones((2, 2))
B = np.ones((2, 2))
np.dot(A,B)

array([[2., 2.],
       [2., 2.]])

SyntaxError: invalid syntax (<ipython-input-64-3db4cef70667>, line 3)